feat: implement covector for publishing changes
tauri-apps/tauri-includedir pull request #4
Opened 2020-06-19 13:00 UTC by jbolda

This implements both the version and publishing sequences from covector. Some of the config isn't actually implemented yet, so "pseudo" config at this point.

This closes #3.

2020-06-20 05:36 UTC, jbolda commented
@nothingismagick we need to add the appropriate secrets and I think this should be set. I think we merge it without any change files to double check the "no change" publish sequence. Then after we can add a change file and try the main publish sequence.

2020-06-23 06:48 UTC, nothingismagick requested changes

2020-06-23 06:48 UTC, nothingismagick commented on .github/workflows/covector-version-or-publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
not sure what this is doing here.

2020-06-23 06:55 UTC, jbolda commented on .github/workflows/covector-version-or-publish.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
copypasta... removed

2020-06-23 06:58 UTC, nothingismagick approved these changes

2020-06-23 06:59 UTC, merged